### ISSUE TITLE
extractors fail

### ISSUE THREAD

**Issue by poldrack** [tyarkoni/pliers#201]
I am having problem getting the extractors from the second README example to work.  here is the code to recreate:

```
from pliers.stimuli import VideoStim
from pliers.extractors import (STFTAudioExtractor, PredefinedDictionaryExtractor, ComplexTextExtractor, ClarifaiAPIExtractor, IndicoAPITextExtractor)
from pliers.filters import FrameSamplingFilter
from pliers.graph import Graph
clips = ['../pliers/pliers/tests/data/video/obama_speech.mp4']
clips = [VideoStim(f) for f in clips]
#nodes=[PredefinedDictionaryExtractor(['subtlexusfrequency/Lg10WF'])]
nodes=[IndicoAPITextExtractor(models=['sentiment'])]
g = Graph(nodes)
result = g.run(clips)

```

using either of those nodes, I get an HTTPError: HTTP Error 401: Not Authorized.  The earlier nodes in the example work fine so it's not a general problem with my setup.

**Comment by qmac** [comment]
Do you have a Wit.ai API KEY set in your environment? Or IBM Bluemix credentials? Or both? Or neither? The problem is probably from within one of those APIs (I've had particular problems with Wit in the past)

**Comment by qmac** [comment]
Sorry, I also should have noted that one of those APIs is being called because of the implicit conversion feature, i.e. given that you're trying to run a text extractor on a video, we first run a speech-to-text API to get text to extract from.

**Comment by poldrack** [comment]
yes, I have the following keys specified as env vars as specified in the readme:
WIT_AI_API_KEY
IBM_USERNAME
IBM_PASSWORD

is there a separate method to test all of the API credentials to make sure they are correct?

**Comment by qmac** [comment]
Unfortunately there is no such method as of now, but it sounds like a useful feature to include. I can't seem to recreate the issue, even when I use old or incorrect authentication for the API, I get a different error. Could you share the full traceback?

**Comment by poldrack** [comment]
here's the traceback for the code above, using commit fa9a9ba - this is being run within a docker container created using https://github.com/poldrack/pliers-docker:

root@71276dfd6946:~/share# python test2.py
[MoviePy] Writing audio in /tmp/tmp82ojdx0m.wav
100%|#######################################| 193/193 [00:00<00:00, 1478.66it/s]
[MoviePy] Done.
Traceback (most recent call last):
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/converters/api.py", line 180, in _query_api
    response = urlopen(request, timeout=None)
  File "/miniconda/envs/py35/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/miniconda/envs/py35/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/miniconda/envs/py35/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/miniconda/envs/py35/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/miniconda/envs/py35/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/miniconda/envs/py35/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Not Authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    result = g.run(clips)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/graph.py", line 124, in run
    results = list(chain(*[self.run_node(n, stim) for n in self.roots]))
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/graph.py", line 124, in <listcomp>
    results = list(chain(*[self.run_node(n, stim) for n in self.roots]))
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/graph.py", line 136, in run_node
    result = node.transformer.transform(stim)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/extractors/base.py", line 20, in transform
    result = super(Extractor, self).transform(stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 46, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 71, in transform
    iters = self._iterate(stims, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 173, in _iterate
    res = self._transform(batch, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 188, in _transform
    return list(super(BatchTransformerMixin, self)._iterate(stims, *args, **kwargs))
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 143, in <genexpr>
    return (t for t in (self.transform(s, *args, **kwargs) for s in stims) if t)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 143, in <genexpr>
    return (t for t in (self.transform(s, *args, **kwargs) for s in stims) if t)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/extractors/base.py", line 20, in transform
    result = super(Extractor, self).transform(stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 46, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 80, in transform
    validated_stim = self._validate(stims)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 106, in _validate
    stim = converter.transform(stim)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 46, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 93, in transform
    result = self._transform(validated_stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/converters/base.py", line 27, in _transform
    return self._convert(stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/converters/multistep.py", line 38, in _convert
    stim = converter.transform(stim)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 46, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/transformers.py", line 93, in transform
    result = self._transform(validated_stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/converters/base.py", line 27, in _transform
    return self._convert(stim, *args, **kwargs)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/converters/api.py", line 123, in _convert
    _json = self._query_api(clip)
  File "/miniconda/envs/py35/lib/python3.5/site-packages/pliers-0.1.1-py3.5.egg/pliers/converters/api.py", line 183, in _query_api
    getattr(e, "reason", "status {0}".format(e.code))))
Exception: recognition request failed: Not Authorized
Exception ignored in: <bound method FFMPEG_VideoReader.__del__ of <moviepy.video.io.ffmpeg_reader.FFMPEG_VideoReader object at 0x7f7ac1cb25c0>>
Traceback (most recent call last):
  File "/miniconda/envs/py35/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py", line 176, in __del__
  File "/miniconda/envs/py35/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py", line 169, in close
  File "/miniconda/envs/py35/lib/python3.5/subprocess.py", line 1523, in terminate
  File "/miniconda/envs/py35/lib/python3.5/subprocess.py", line 1518, in send_signal
TypeError: 'NoneType' object is not callable

**Comment by qmac** [comment]
@poldrack I noticed in the docker README you put `joe@schmo.edu` under IBM username. It should be the case that this looks more like an encrypted string, I suspect that you may be using your IBM Bluemix/Cloud login credentials. The credentials should be specific to the Speech-To-Text service (you must enable the service for your account and generate the credentials). Let me know if you were already doing this.

This does bring up a good issue that we should look for a more specific environment variable like `IBM_SPEECH_API_USERNAME`.

**Comment by poldrack** [comment]
good catch, that is indeed what I was doing.  I just enabled the speech-to-text service and put those credentials into my environment variables (IBM_USERNAME and IBM_PASSWORD), but I am still getting a "Not authorized" message.  is there a better way to test which specific API is failing?

**Comment by qmac** [comment]
Hmm there probably is a better way to catch errors and give more information on which pliers transformer is responsible. @tyarkoni thoughts on this?

Based on the traceback (`pliers/converters/api.py", line 180, in _query_api`) this particular case is probably still in the IBM speech-to-text one.

**Comment by poldrack** [comment]
would you mind trying it out within the docker container using your credentials so that we can see whether it's something specific to that environment?

**Comment by poldrack** [comment]
BTW - just tested my IBM credentials using their example via curl and they work fine

**Comment by qmac** [comment]
I was able to run that code snippet within the docker container cleanly without the authorization error (using my credentials).

**Comment by poldrack** [comment]
odd, can you tell me specifically which environment variables you defined?

**Comment by qmac** [comment]
I just followed the README and used
WIT_AI_API_KEY
IBM_USERNAME
IBM_PASSWORD
INDICO_APP_KEY
GOOGLE_APPLICATION_CREDENTIALS="/root/share/googleapi.json"
CLARIFAI_API_KEY

**Comment by poldrack** [comment]
ok - made a bit of progress - it seems that putting quotation marks around the API keys may have been causing a problem.  it gets a bit further but now I am getting another error:


Stim: 0it [00:00, ?it/s][MoviePy] Writing audio in /tmp/tmp24w38dr0.wav
                                                                               [MoviePy] Done.##############################| 193/193 [00:00<00:00, 1010.69it/s]
Stim: 1it [00:04,  4.70s/it]
Exception ignored in: <bound method FFMPEG_AudioReader.__del__ of <moviepy.audio.io.readers.FFMPEG_AudioReader object at 0x7fbf8faa06a0>>
Traceback (most recent call last):
  File "/miniconda/envs/py35/lib/python3.5/site-packages/moviepy/audio/io/readers.py", line 240, in __del__
  File "/miniconda/envs/py35/lib/python3.5/site-packages/moviepy/audio/io/readers.py", line 151, in close_proc
  File "/miniconda/envs/py35/lib/python3.5/subprocess.py", line 1523, in terminate
  File "/miniconda/envs/py35/lib/python3.5/subprocess.py", line 1518, in send_signal
TypeError: 'NoneType' object is not callable

**Comment by qmac** [comment]
Does this actually break the snippet? This exception appears sometimes in moviepy but it is usually ignored and things execute cleanly.

**Comment by poldrack** [comment]
you are indeed correct, I can now run the entire example 2 from the readme.  hard to believe that we both wasted so much time over some effing quotation marks...

**Comment by tyarkoni** [comment]
Re: testing API failure, I think we should definitely add a utility function to test this more systematically. Will open a new issue for discussion.
