### ISSUE TITLE
IBMSpeechAPIConverter error

### ISSUE THREAD

**Issue by mgxd** [tyarkoni/pliers#238]
```python
"""
Adapted from pliers example
:: http://tyarkoni.github.io/pliers/graphs.html#listing-1 ::

"""
from pliers.stimuli import VideoStim
from pliers.converters import IBMSpeechAPIConverter
from pliers.extractors import IndicoAPITextExtractor
import os

video = VideoStim("obama.mp4")
#video = VideoStim("trailer.mp4")

# ensure environmental variables are correct
print('username: {}'.format(os.getenv('IBM_USERNAME')))
print('password: {}'.format(os.getenv('IBM_PASSWORD')))

print('Transcribing speech with IBM')
# Run each image through IBM's text detection API
# Google complained about >1 min of audio
transcriber = IBMSpeechAPIConverter()
transcripts = transcriber.transform(video)

print('Processing speech sentiment')
# Apply Indico sentiment analysis extractor
indico = IndicoAPITextExtractor(models=['sentiment'])
sentiment_results = indico.transform(transcripts)
```
When run
```
username: xxxxx@xxxx
password: xxxxx
Transcribing speech with IBM
[MoviePy] Writing audio in /tmp/tmpxvacczty.wav
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 105/105 [00:00<00:00, 1805.67it/s]
[MoviePy] Done.
Traceback (most recent call last):
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/api.py", line 173, in _query_api
    response = urlopen(request, timeout=None)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 32] Broken pipe>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_pliers.py", line 28, in <module>
    transcripts = transcriber.transform(video)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/transformers/base.py", line 55, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/transformers/base.py", line 125, in transform
    return self.transform(validated_stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/transformers/base.py", line 55, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/transformers/base.py", line 127, in transform
    result = self._transform(validated_stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/base.py", line 27, in _transform
    return self._convert(stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/api.py", line 111, in _convert
    _json = self._query_api(clip)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/api.py", line 179, in _query_api
    "recognition connection failed: {0}".format(e.reason))
Exception: recognition connection failed: [Errno 32] Broken pipe
```

This looks like a problem with requests, but am still seeing the problem after upgrading to the latest - any ideas?

**Comment by tyarkoni** [comment]
I can't reproduce this, unfortunately... equivalent code works fine on my end, and every step here is also tested on linux on travis-ci. @qmac can weigh in, but it's hard to say what's going on.

Two things you could try, to see if we can localize the problem better:
* Switch out the `IBMSpeechAPIConverter` for the `GoogleSpeechAPIConverter`
* Skip the transcription step and pass a `TextStim` to the indico extractor

The latter should definitely work, and whether or not the former works will give us a clue as to where the problem is being triggered.

**Comment by mgxd** [comment]
@tyarkoni ah, I was missing the `watson-developer-cloud` package!

Now the error has changed - perhaps I have to do some additional steps on IBM's side?

```
Traceback (most recent call last):
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/api.py", line 173, in _query_api
    response = urlopen(request, timeout=None)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Not Authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_pliers.py", line 34, in <module>
    transcripts = transcriber.transform(audio)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/transformers/base.py", line 55, in wrapper
    result = transform(self, stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/transformers/base.py", line 127, in transform
    result = self._transform(validated_stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/base.py", line 27, in _transform
    return self._convert(stim, *args, **kwargs)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/api.py", line 111, in _convert
    _json = self._query_api(clip)
  File "/home/mathias/miniconda2/envs/dev3/lib/python3.6/site-packages/pliers/converters/api.py", line 176, in _query_api
    getattr(e, "reason", "status {0}".format(e.code))))
Exception: recognition request failed: Not Authorize
```

**Comment by tyarkoni** [comment]
Not 100% sure, but that looks to me like an API key issue. Are you sure you're entering the right key/password combo? The IBM keys are unfortunately service-specific, so it's not good enough AFAIK to have an IBM key--you need to make sure it's for exactly the right service (speech-to-text). 

Any idea how you ended up without the `watson-developer-cloud`? I'm asking because I didn't even realize that was a dependency (I'm guessing it's normally installed by `speech_recognition`, which is the interface we use for the IBM Transformer), and I just want to make sure this isn't going to be a common occurrence. (If it is, we'll just add it to optional-requirements.txt).

**Comment by mgxd** [comment]
Yep - this was just a case of not grabbing the proper [service credentials](https://github.com/watson-developer-cloud/python-sdk#getting-the-service-credentials) - sorry for the noise!

**Comment by tyarkoni** [comment]
It occurs to me that it would be quite useful to add an example string to the API keys table in the docs, so users can see what the expected format is. I've run into confusion with this myself on a couple of occasions. Will open an issue.

**Comment by tyarkoni** [comment]
No worries--it's helpful to know where the bottlenecks are, and this led to opening #239, which should help. :)

**Comment by qmac** [comment]
@mgxd Just to check, you want to do audio->text transcription on the video's audio right? Just making sure cause the comment in your code says `Run each image through IBM's text detection API`.

**Comment by mgxd** [comment]
Whoops - yes! I think there is a similar comment within [the example](http://tyarkoni.github.io/pliers/graphs.html#listing-1) that should be fixed as well

**Comment by qmac** [comment]
Haha yep that should be fixed @tyarkoni
